server:
  addr: ":5001"

token:
  issuer: "docker-auth"
  expiration: 900
  certificate: "/certs/server.crt"
  key: "/certs/server.key"

users:
  "ihormac":
    password: "$2y$05$51vJ7Hn0CWJakRtbeXKtHuIWf/PZXUg4sTQyc.PnJq7koYMkSs3wq"

acl:
  - match: {account: ""}
    actions: ["pull"]
    comment: "Anonymous users can pull"
  - match: {account: "/.+/"}
    actions: ["*"]
    comment: "Authenticated users can do anything"
